config/routes.rb
Contribute::Application.routes.draw do
  resources :causes

  resources :question_lists

  get "static_page/index"

  resources :customers
  resources :static_pages

  root :to => 'static_page#index'

end

app/models/cause.rb
class Cause < ActiveRecord::Base
  attr_accessible :logo, :name
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :email
end

app/models/question_list.rb
class QuestionList < ActiveRecord::Base
  attr_accessible :for, :free_text, :kind, :purpose, :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  protected
  def admin
    redirect_to root_path
  end
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController
  # GET /causes
  # GET /causes.json
  def index
    @causes = Cause.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @causes }
    end
  end

  # GET /causes/1
  # GET /causes/1.json
  def show
    @cause = Cause.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/new
  # GET /causes/new.json
  def new
    @cause = Cause.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/1/edit
  def edit
    @cause = Cause.find(params[:id])
  end

  # POST /causes
  # POST /causes.json
  def create
    @cause = Cause.new(params[:cause])

    respond_to do |format|
      if @cause.save
        format.html { redirect_to @cause, notice: 'Cause was successfully created.' }
        format.json { render json: @cause, status: :created, location: @cause }
      else
        format.html { render action: "new" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /causes/1
  # PUT /causes/1.json
  def update
    @cause = Cause.find(params[:id])

    respond_to do |format|
      if @cause.update_attributes(params[:cause])
        format.html { redirect_to @cause, notice: 'Cause was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /causes/1
  # DELETE /causes/1.json
  def destroy
    @cause = Cause.find(params[:id])
    @cause.destroy

    respond_to do |format|
      format.html { redirect_to causes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  helper_method :admin
  before_filter :admin, :except => ["create"]
  respond_to :js
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
       # format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
      #  format.json { render json: @customer, status: :created, location: @customer }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/question_lists_controller.rb
class QuestionListsController < ApplicationController
  layout "admin"
  # GET /question_lists
  # GET /question_lists.json
  def index
    @question_lists = QuestionList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @question_lists }
    end
  end

  # GET /question_lists/1
  # GET /question_lists/1.json
  def show
    @question_list = QuestionList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question_list }
    end
  end

  # GET /question_lists/new
  # GET /question_lists/new.json
  def new
    @question_list = QuestionList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question_list }
    end
  end

  # GET /question_lists/1/edit
  def edit
    @question_list = QuestionList.find(params[:id])
  end

  # POST /question_lists
  # POST /question_lists.json
  def create
    @question_list = QuestionList.new(params[:question_list])

    respond_to do |format|
      if @question_list.save
        format.html { redirect_to @question_list, notice: 'Question list was successfully created.' }
        format.json { render json: @question_list, status: :created, location: @question_list }
      else
        format.html { render action: "new" }
        format.json { render json: @question_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /question_lists/1
  # PUT /question_lists/1.json
  def update
    @question_list = QuestionList.find(params[:id])

    respond_to do |format|
      if @question_list.update_attributes(params[:question_list])
        format.html { redirect_to @question_list, notice: 'Question list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_lists/1
  # DELETE /question_lists/1.json
  def destroy
    @question_list = QuestionList.find(params[:id])
    @question_list.destroy

    respond_to do |format|
      format.html { redirect_to question_lists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  before_filter :admin, :except => ["index"]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/question_lists_helper.rb
module QuestionListsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/causes/_form.html.erb
<%= form_for @cause, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :name, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :logo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :logo, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                causes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/causes/edit.html.erb
<%- model_class = Cause -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/causes/index.html.erb
<%- model_class = Cause -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:logo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @causes.each do |cause| %>
      <tr>
        <td><%= link_to cause.id, cause_path(cause) %></td>
        <td><%= cause.name %></td>
        <td><%= cause.logo %></td>
        <td><%=l cause.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cause_path(cause), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cause_path(cause),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cause_path,
            :class => 'btn btn-primary' %>

app/views/causes/new.html.erb
<%- model_class = Cause -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/causes/show.html.erb
<%- model_class = Cause -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @cause.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:logo) %>:</strong></dt>
  <dd><%= @cause.logo %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              causes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cause_path(@cause), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cause_path(@cause),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :email, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/customers/create.js.erb
$('#signup-form').html("<p class='notice' style='font-size:150%;padding:10px'>We got you covered !!!! Please follow our social channels to support us ...</p>");

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, customer_path(customer) %></td>
        <td><%= customer.email %></td>
        <td><%=l customer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @customer.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/_index.erb
<style type="text/css" media="screen">
/* GLOBAL STYLES
-------------------------------------------------- */
/* Padding below the footer and lighter body text */

body {
  padding-bottom: 40px;
  color: #5a5a5a;
}

#bio{
    width:100%;
}

/* CUSTOMIZE THE NAVBAR
-------------------------------------------------- */

/* Special class on .container surrounding .navbar, used for positioning it into place. */
.navbar-wrapper {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  z-index: 10;
  margin-top: 20px;
  margin-bottom: -90px; /* Negative margin to pull up carousel. 90px is roughly margins and height of navbar. */
}
.navbar-wrapper .navbar {

}

/* Remove border and change up box shadow for more contrast */
.navbar .navbar-inner {
  border: 0;
  -webkit-box-shadow: 0 2px 10px rgba(0,0,0,.25);
  -moz-box-shadow: 0 2px 10px rgba(0,0,0,.25);
  box-shadow: 0 2px 10px rgba(0,0,0,.25);
}

/* Downsize the brand/project name a bit */
.navbar .brand {
  padding: 14px 20px 16px; /* Increase vertical padding to match navbar links */
  font-size: 16px;
  font-weight: bold;
  text-shadow: 0 -1px 0 rgba(0,0,0,.5);
}

/* Navbar links: increase padding for taller navbar */
.navbar .nav > li > a {
  padding: 15px 20px;
}

/* Offset the responsive button for proper vertical alignment */
.navbar .btn-navbar {
  margin-top: 10px;
}



/* CUSTOMIZE THE CAROUSEL
-------------------------------------------------- */

/* Carousel base class */
.carousel {
  margin-bottom: 60px;
}

.carousel .container {
  position: relative;
  z-index: 9;
}
.carousel-control {
  height: 80px;
  margin-top: 0;
  font-size: 120px;
  text-shadow: 0 1px 1px rgba(0,0,0,.4);
  background-color: transparent;
  border: 0;
  z-index: 10;
}
.carousel .item {
  height: 500px;
}
.carousel img {
  position: absolute;
  top: 0;
  left: 0;
  min-width: 100%;
  height: 500px;
}
.carousel-caption {
  background-color: transparent;
  position: static;
  width: auto;
  padding: 0 20px;
  margin-top: 200px;
}
.carousel-caption h1,
.carousel-caption .lead {
  margin: 0;
  line-height: 1.25;
  color: #fff;
  text-shadow: 0 1px 1px rgba(0,0,0,.4);
}
.carousel-caption .btn {
 # margin-top: 10px;
}

/* MARKETING CONTENT
-------------------------------------------------- */

/* Center align the text within the three columns below the carousel */
.marketing .span4 {
  text-align: center;
}
.marketing h2 {
  font-weight: normal;
}
.marketing .span4 p {
  margin-left: 10px;
  margin-right: 10px;
}


/* Featurettes
------------------------- */

.featurette-divider {
  margin: 80px 0; /* Space out the Bootstrap <hr> more */
}
.featurette {
  padding-top: 120px; /* Vertically center images part 1: add padding above and below text. */
  overflow: hidden; /* Vertically center images part 2: clear their floats. */
}
.featurette-image {
  margin-top: -120px; /* Vertically center images part 3: negative margin up the image the same amount of the padding to center it. */
}

/* Give some space on the sides of the floated elements so text doesn't run right into it. */
.featurette-image.pull-left {
  margin-right: 40px;
}
.featurette-image.pull-right {
  margin-left: 40px;
}

/* Thin out the marketing headings */
.featurette-heading {
  font-size: 50px;
  font-weight: 300;
  line-height: 1;
  letter-spacing: -1px;
}



/* RESPONSIVE CSS
-------------------------------------------------- */

@media (max-width: 979px) {

  .container.navbar-wrapper {
    margin-bottom: 0;
    width: auto;
  }
  .navbar-inner {
    border-radius: 0;
    margin: -20px 0;
  }

  .carousel .item {
    height: 500px;
  }
  .carousel img {
    width: auto;
    height: 500px;
  }

  .featurette {
    height: auto;
    padding: 0;
  }
  .featurette-image.pull-left,
  .featurette-image.pull-right {
    display: block;
    float: none;
    max-width: 40%;
    margin: 0 auto 20px;
  }
}


@media (max-width: 767px) {

  .navbar-inner {
    margin: -20px;
  }

  .carousel {
    margin-left: -20px;
    margin-right: -20px;
  }
  .carousel .container {

  }
  .carousel .item {
    height: 300px;
  }
  .carousel img {
    height: 300px;
  }
  .carousel-caption {
    width: 65%;
    padding: 0 70px;
    margin-top: 100px;
  }
  .carousel-caption h1 {
    font-size: 30px;
  }
  .carousel-caption .lead,
  .carousel-caption .btn {
    font-size: 18px;
  }

  .marketing .span4 + .span4 {
    margin-top: 40px;
  }

  .featurette-heading {
    font-size: 30px;
  }
  .featurette .lead {
    font-size: 18px;
    line-height: 1.5;
  }

}

.navbar-wrapper{
	margin:0;
	padding:0;
	#background-color: #16333f !important;
}
.navbar-inner{
	background-color: #16333f !important;
}
.navbar{
	background-color: #16333f !important;
}
.navbar-inverse{
	background-color: #16333f !important;
}

#logo{
	height:15%;
	width:20%;
	margin-left: 100px;
}

.thumbnail > img {
	 height:108px;
	width:109px
}
.thumbnail{
	border:none;
	text-align:center;
	box-shadow:none;
}
.thumbnails > li {
    display: inline-block;
    float: left; /* this is the part that makes it work */
}

#signup-form{
	padding-top:50px;
	text-align:center;
}
#signup-email{
	width:700px;
	font: 150% "Lucida Grande", "Trebuchet MS", Verdana, sans-serif;
}

#logo{
	height:15%;
	width:20%;
	margin-left: 100px;
}
textarea{
	width:99%;
	max-height:50px;
}
.page-header{

}
</style>

app/views/layouts/_navbar.html.erb
<div class="navbar-wrapper">
<div class="container-fluid" style="margin:0;padding:0">
<div class="navbar navbar-inverse">
<div class="navbar-inner">
<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</button>
	<%= image_tag "contribute-logo.png", :id=> "logo", :class=>"brand" , :style=>"text-align:center"%>
	<div class="nav-collapse in collapse pull-right" style="height: auto">
	<ul class="nav">
	<li class="active">
	<a href="#"></a>
	</li>
	<li>
	<a href="#about"></a>
	<%= link_to "Questions" , question_lists_path%>
	</li>
	<li>
	<a href="#contact"></a>
	</li>
	</ul>
</div>
</div>
</div>
</div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contribute</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
<style type="text/css" media="screen">

</style>

</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=137591512981188";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40495942-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<%= render 'layouts/index' %>
<div class="navbar-wrapper">
<div class="container-fluid" style="margin:0;padding:0">
<div class="navbar navbar-inverse">
<div class="navbar-inner">
<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</button>
	<%= image_tag "contribute-logo.png", :id=> "logo", :class=>"brand " , :style=>"text-align:center"%>
	<div class="nav-collapse in collapse pull-right" style="height: auto">
	<ul class="nav">
	<li class="active">
	<a href="#"></a>
	</li>
	<li>
	<a href="#">Non-Profits</a>
	</li>
	<li>
	<a href="#contact">Volunteers</a>
	</li>
	<li>
	<a href="#contact">Causes</a>
	</li>
	<li>
		<%= link_to "Questions" , question_lists_path %>
	</li>
	</ul>
</div>
</div>
</div>
</div>

</div>
<div class="container-fluid" style="margin-top:75px">
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contribute</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
<style type="text/css" media="screen">
	font-family: Merriweather, sans-serif !important;
</style>

</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=137591512981188";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40495942-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<%= render 'layouts/index' %>
<%= render 'layouts/navbar' %>
<div class="container-fluid" style="margin-top:75px">
	<%= yield %>
	</div>

</body>
</html>

app/views/question_lists/edit.html.erb
<%- model_class = QuestionList -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/question_lists/index.html.erb
<%- model_class = QuestionList -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:question) %></th>
      <th><%= model_class.human_attribute_name(:for) %></th>
      <th><%= model_class.human_attribute_name(:purpose) %></th>
      <th><%= model_class.human_attribute_name(:kind) %></th>
      <th><%= model_class.human_attribute_name(:free_text) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @question_lists.each do |question_list| %>
      <tr>
        <td><%= link_to question_list.id, question_list_path(question_list) %></td>
        <td><%= question_list.question %></td>
        <td><%= question_list.for %></td>
        <td><%= question_list.purpose %></td>
        <td><%= question_list.kind %></td>
        <td><%= question_list.free_text %></td>
        <td><%=l question_list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_question_list_path(question_list), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      question_list_path(question_list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_question_list_path,
            :class => 'btn btn-primary' %>

app/views/question_lists/new.html.erb
<%- model_class = QuestionList -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/static_page/index.js.erb
$('#submit').on('click', function() {
  // Act on the event
	
});